import { Rubik } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar";
import Footer from "@/components/Footer";

const inter = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "Home page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />

        <div className="min-h-screen"> {children}</div>

        <Footer />
      </body>
    </html>
  );
}
